permissions:
  contents: write
  
name: Ejecutar script y actualizar archivo en OneDrive

on:
  schedule:
    - cron: '0 */6 * * *'
    # Se ejecuta cada 6 horas (UTC)
  workflow_dispatch:

jobs:
  run-and-update:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: List files in directory (pre-run)
        run: ls -la

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script de actualización del Excel
        id: update_excel
        run: python main.py

      - name: List files in directory (post-run)
        run: ls -la

      - name: Enviar archivo actualizado a OneDrive
        run: |
          echo "Enviando archivo: ${{ steps.update_excel.outputs.file_path }}"
          curl -X POST "https://prod-233.westeurope.logic.azure.com:443/workflows/a974d6fb1b994402a09de17b4a888ad4/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=uPpft8qBCQch3TBQhnY6TtqKdRiaBXLVC7RJ0nZUODg" \
          -H "Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" \
          --data-binary "@${{ steps.update_excel.outputs.file_path }}"
